name: Build armv7_musl

on: [workflow_dispatch]

env:
  DOTNET_SDK_VERSION: '9.0.*'
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  set-date:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.get_date.outputs.date }}
    steps:
      - name: Get Date in UTC+8
        id: get_date
        run: echo "date=$(date -u -d '8 hours' +'%Y%m%d')" >> "$GITHUB_OUTPUT"
        
  build-linux-armv7:
    runs-on: ubuntu-latest
    needs: set-date
    container: messense/rust-musl-cross:armv7-musleabihf  # 使用预配置的Docker镜像
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
      - name: Publish for ARMv7 (musl)
        run: |
          dotnet publish BBDown -r linux-arm -c Release -o artifact-armv7  # 指定ARMv7运行时
      - name: Package artifact
        run: |
          cd artifact-armv7
          zip ../BBDown_${{ needs.set-date.outputs.date }}_linux-armv7.zip BBDown
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BBDown_linux-armv7
          path: BBDown_${{ needs.set-date.outputs.date }}_linux-armv7.zip
