name: Build armv7_musl

on: [workflow_dispatch]

env:
  DOTNET_SDK_VERSION: '9.0.*'
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  set-date:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.get_date.outputs.date }}
    steps:
      - name: Get Date in UTC+8
        id: get_date
        run: echo "date=$(date -u -d '8 hours' +'%Y%m%d')" >> "$GITHUB_OUTPUT"
        
  # 新增矩阵策略
  build-linux:
    runs-on: ubuntu-latest
    needs: set-date
    strategy:
      matrix:
        target: [linux-arm]
    steps:
      - uses: actions/checkout@v4
      - name: Setup musl toolchain (ARMv7 only)
        if: matrix.target == 'linux-arm'
        run: |
          docker run --rm -v $(pwd):/work messense/rust-musl-cross:armv7-musleabihf
      - name: Publish
        run: dotnet publish BBDown -r ${{ matrix.target }} -c Release -o artifact-${{ matrix.target }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BBDown_${{ matrix.target }}
          path: BBDown_${{ needs.set-date.outputs.date }}_${{ matrix.target }}.zip
