name: Build armv7_musl
on: [workflow_dispatch]

env:
  DOTNET_SDK_VERSION: '9.0.*'
  ALPINE_VERSION: '3.21'  # 选择与.NET 9.0兼容的Alpine版本

jobs:
  set-date:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.get_date.outputs.date }}
    steps:
      - name: Get UTC+8 Date
        id: get_date
        run: echo "date=$(date -u -d '8 hours' +'%Y%m%d')" >> "$GITHUB_OUTPUT"

  build-alpine:
    runs-on: ubuntu-latest
    needs: set-date
    strategy:
      matrix:
        arch: [armv7]  # 支持x64/arm64/armv7架构 [x64, arm64, armv7]
    steps:
      # 使用Alpine容器化环境
      - name: Setup Alpine
        uses: jirutka/setup-alpine@v1  # 容器化Alpine环境
        with:
          branch: v${{ env.ALPINE_VERSION }}
          arch: ${{ matrix.arch }}  # 自动处理QEMU模拟
          packages: |
            dotnet9-sdk
            gcc
            musl-dev
            zlib-dev
            # ARMv7需额外依赖
            ${{ matrix.arch == 'armv7' && 'gcc-arm-linux-gnueabihf' || '' }}

      - uses: actions/checkout@v4

      # 配置.NET环境 (Runs inside the Alpine container)
      - name: Setup .NET SDK
        run: |
          apk update && apk add dotnet9-sdk
        shell: alpine.sh # Ensure this runs within the Alpine environment

      # 编译发布 (Runs inside the Alpine container)
      - name: Publish for Alpine
        run: |
          RID="linux-musl-${{ matrix.arch }}"  # Alpine使用musl标识
          dotnet publish BBDown -r $RID -c Release \
            -p:PublishAot=true \  # 启用原生AOT
            -p:StripSymbols=false \
            -o artifact-$RID
        shell: alpine.sh # Ensure this runs within the Alpine environment

      # 打包上传 (Runs inside the Alpine container)
      - name: Package Artifacts
        run: |
          cd artifact-linux-musl-${{ matrix.arch }}
          zip ../BBDown_${{ needs.set-date.outputs.date }}_alpine-${{ matrix.arch }}.zip BBDown
        shell: alpine.sh # Ensure this runs within the Alpine environment

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BBDown_alpine-${{ matrix.arch }}
          path: BBDown_${{ needs.set-date.outputs.date }}_alpine-${{ matrix.arch }}.zip
