name: Build for OpenWrt x64

on: [workflow_dispatch]

env:
  DOTNET_SDK_VERSION: '9.0.*'

jobs:
  build-openwrt-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Publish for OpenWrt (musl)
        run: |
          dotnet publish BBDown -r linux-musl-x64 -c Release --self-contained true -o artifact-x64 # 针对 musl libc 的 x64 构建


      - name: Package for OpenWrt
        run: |
          cd artifact-x64
          # tar -czvf BBDown_openwrt_x86.tar.gz * # 使用 tar.gz 压缩
          zip ../BBDown_${{ needs.set-date.outputs.date }}_OpenWrt-x64.zip BBDown


      - name: Upload Artifact [OpenWrt-x64]
        uses: actions/upload-artifact@v3.1.3
        with:
          name: BBDown_OpenWrt-x64
          path: BBDown_${{ needs.set-date.outputs.date }}_OpenWrt-x64.zip

