name: Build Linux x86

on: [push, workflow_dispatch]

env:
  DOTNET_SDK_VERSION: '9.0.*'
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  set-date:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.get_date.outputs.date }}
    steps:
      - name: Get Date in UTC+8
        id: get_date
        run: echo "date=$(date -u -d '8 hours' +'%Y%m%d')" >> "$GITHUB_OUTPUT"

  build-linux-x86:
    runs-on: ubuntu-latest
    needs: set-date
    steps:
      - name: setup deb822 repos
        run: |
          # 确保源包含 i386 架构
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 lib32stdc++6 # 安装 32 位库及其他必要依赖
          sudo apt-get install -y curl wget libicu-dev libcurl4-openssl-dev zlib1g-dev libkrb5-dev clang llvm # 安装构建工具和依赖

      - uses: actions/checkout@v1

      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Publish [linux-x86]
        run: dotnet publish BBDown -r linux-x86 -c Release -o artifact

      - name: Package [linux-x86]
        run: |
          cd artifact
          zip ../BBDown_${{ needs.set-date.outputs.date }}_linux-x86.zip BBDown

      - name: Upload Artifact [linux-x86]
        uses: actions/upload-artifact@v3.1.3
        with:
          name: BBDown_linux-x86
          path: BBDown_${{ needs.set-date.outputs.date }}_linux-x86.zip
